# Generated by Django 4.2.23 on 2026-10-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('faction', models.CharField(max_length=50)),
                ('loyalty', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('card_type', models.CharField(max_length=50)),
                ('cost', models.SmallIntegerField(blank=True, null=True)),
                ('command', models.SmallIntegerField(blank=True, null=True)),
                ('attack', models.SmallIntegerField(blank=True, null=True)),
                ('health', models.SmallIntegerField(blank=True, null=True)),
                ('shields', models.SmallIntegerField(blank=True, null=True)),
                ('cycle', models.CharField(max_length=200)),
                ('war_pack', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200, null=True)),
                ('useful_quantities', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sector', models.CharField(max_length=200, null=True)),
                ('green', models.BooleanField(blank=True, null=True)),
                ('blue', models.BooleanField(blank=True, null=True)),
                ('red', models.BooleanField(blank=True, null=True)),
                ('resources', models.SmallIntegerField(blank=True, null=True)),
                ('cards', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RulesClarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('updated', models.DateField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='cards.card')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CardFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated', models.DateField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cards.card')),
                ('related_cards', models.ManyToManyField(blank=True, related_name='mentioned_in_faqs', to='cards.card')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
