# Generated by Django 4.2.23 on 2026-10-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardfaq',
            constraint=models.UniqueConstraint(fields=('card', 'order'), name='uniq_faq_card_order'),
        ),
        migrations.AddConstraint(
            model_name='rulesclarification',
            constraint=models.UniqueConstraint(fields=('card', 'order'), name='uniq_clarification_card_order'),
        ),
    ]
